app:
    build: tools
    tty: true
    volumes:
        - ./app:/var/www/app
        - ./logs/slimphp:/var/www/app/logs
db:
    image: mysql:5.7
    ports:
        - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: slimapp
        MYSQL_USER: root
        MYSQL_PASSWORD: root
php:
    build: php-fpm
    volumes_from:
        - app
    links:
        - db
    ports:
        - 9000:9000
    volumes:
        - ./php-fpm:/usr/local/etc/php/conf.d/
    working_dir: /var/www/app/public
nginx:
    image: nginx:1.10.0-alpine
    ports:
        - 9123:9123
    links:
        - php
    volumes_from:
        - app
    volumes:
        - ./logs/nginx/:/var/log/nginx/
        - ./nginx/conf/:/etc/nginx/conf.d/
